# Generated by Django 5.1.7 on 2025-03-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
