# Generated by Django 5.1.7 on 2025-03-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_adminannouncement_delete_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cancel_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
    ]
