# Generated by Django 5.1.7 on 2025-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_adminearnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminearnings',
            name='booking_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='adminearnings',
            name='cancel_earnings',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
