# Generated by Django 5.1.7 on 2025-03-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vendor_approval',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
