# Generated by Django 5.1.7 on 2025-03-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_booking_vendor_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_approval',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
