# Generated by Django 5.1.7 on 2025-03-22 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_booking_payment_approval'),
        ('vendor', '0011_alter_vendor_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_people', models.PositiveIntegerField()),
                ('event_name', models.CharField(max_length=255)),
                ('venue_address', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('event_hours', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_date', models.DateTimeField()),
                ('cancelled_date', models.DateTimeField(auto_now_add=True)),
                ('select_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorserviceprice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor')),
            ],
        ),
    ]
