# Generated by Django 5.1.7 on 2025-03-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_cancelledbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_approval',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
