# Generated by Django 5.1.7 on 2025-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vendor_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
