# Generated by Django 5.1.7 on 2025-03-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_booking_vendor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_status',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
