# Generated by Django 5.1.7 on 2025-03-25 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_booking_booked_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_status',
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cancelledbooking',
            name='user_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
